#pragma once
#include "Module.h"

class Spammer : public IModule {
private:
	int Odelay = 0;
	bool bypass = false;
	bool prefix = true;
	int delay = 2;
	int length = 8;
	int changer = 0;
	std::string message = ">Kek.Club+ Owns You";
	std::string message2 = ">EZ NN";
	std::string message3 = ">You simply can't beat Kek.Club+";
	std::string message4 = ">You can't beat Kek.Club+";
	std::string message5 = ">I'm unironically the best player on. ";
	std::string message6 = ">Keep crying :yawn:";
	std::string message7 = ">Sit Dog";
	std::string message8 = ">1v1 or cope";
	std::string message9 = ">Come to 0,0 or swat";
	std::string message10 = ">Compare funds or dodge";
	std::string message11 = ">Who are you????";
	std::string message12 = ">T R A S H E D";
	std::string message13 = ">Go ahead beat me";
	std::string message14 = ">Kek.Club+ owns you";
	std::string message15 = ">So bad";
	std::string message16 = ">Keep coping and seething";
	std::string message17 = ">Kek.Club+ destroying famlies since 2021";
	std::string message18 = ">EW what are you";
	std::string message19 = ">slanted eyed braindead monkeys";
	std::string message20 = ">Whatever you say greaseball";
	std::string message21 = ">Black is bad";
	std::string message22 = "><--Owns the server";
	std::string message23 = ">freak ezzz";
	std::string message24 = ">dumb pizza faced loser";
	std::string message25 = ">nice iq";
	std::string message26 = ">quit the game retard XDDDDDDDDD";
	std::string message27 = ">Best Client LOL keep coping";
	std::string message28 = ">why is this server so easy?????";
	std::string message29 = ">random stop talking";
	std::string message30 = ">GANG BDK";
	std::string message31 = ">Bypassing your server :yawn:";
	std::string message32 = ">Smells like fried chicken ew";
	std::string message33 = ">Untouchable";
	std::string message34 = ">take a shower pooron lol";
	std::string message35 = ">winning all day";
	std::string message36 = ">stay losing nn";
	std::string message37 = ">get yo troll ass outta here";
	std::string message38 = ">sooooooooooooo baddddddddddddddddddddddd";
	std::string message39 = ">who what you still talking?";
	std::string message40 = ">nasty ass orge";
	std::string message41 = ">sit down nn";
	std::string message42 = ">ww";
	std::string message43 = ">i win again :yawn:";
	std::string message44 = ">uninstall or swat";
	std::string message45 = ">hush mode shitter";
	std::string message46 = ">where your base go bro";
	std::string message47 = ">ill go easy on you.... jk";
	std::string message48 = ">keep fighting nn";
	std::string message49 = ">just quit or keep dying";
	std::string message50 = ">*monkey noises*";
	std::string message51 = ">hang yourself incel";
	std::string message52 = ">you are so trash uninstall";
	std::string message53 = ">i am the best";
	std::string message54 = ">iq where";
	std::string message55 = ">ITS MY FAVORITE 3RD WORLD WONDER";
	std::string message56 = ">stay ez stay mad stay cope";
	std::string message57 = ">LOL KEKLESS SO TRASHHHHHH";
	std::string message58 = ">imagine not being known";
	std::string message59 = ">LOL keep running nn";
	std::string message60 = ">whos speaking n1? thats what i thought";
	std::string message61 = ">kys retard LOLZ";
	std::string message62 = ">EZZZZZZZZZZZ";
	std::string message63 = ">crystal aura too good?";
	std::string message64 = ">pride month is over fags";
	std::string message65 = ">nice iq pooron";
	std::string message66 = ">eat shit";
	std::string message67 = ">log faster kek";
	std::string message68 = ">easist kill ever";
	std::string message69 = ">pooron incel cant afford a shower LOL";
	std::string message70 = ">i am the best";
	std::string message71 = ">i am so much better than you LOLZ";
	std::string message72 = ">GANGGGGGGGGGGG";
	std::string message73 = ">smh cringe newfags get blocked";
	std::string message74 = ">keep barking nn dog";
	std::string message75 = ">Bros so cringe they dying LOL";
	std::string message76 = ">I am the king LOL bow down";
	std::string message77 = ">bow down doggie";

public:
	Spammer();
	~Spammer();

	inline std::string& getMessage() { return message; };
	inline std::string& getMessage2() { return message2; };
	inline std::string& getMessage3() { return message3; };
	inline std::string& getMessage4() { return message4; };
	inline std::string& getMessage5() { return message5; };
	inline std::string& getMessage6() { return message6; };
	inline std::string& getMessage7() { return message7; };
	inline std::string& getMessage8() { return message8; };
	inline std::string& getMessage9() { return message9; };
	inline std::string& getMessage10() { return message10; };
	inline std::string& getMessage11() { return message11; };
	inline std::string& getMessage12() { return message12; };
	inline std::string& getMessage13() { return message13; };
	inline std::string& getMessage14() { return message14; };
	inline std::string& getMessage15() { return message15; };
	inline std::string& getMessage16() { return message16; };
	inline std::string& getMessage17() { return message17; };
	inline std::string& getMessage18() { return message18; };
	inline std::string& getMessage19() { return message19; };
	inline std::string& getMessage20() { return message20; };
	inline std::string& getMessage21() { return message21; };
	inline std::string& getMessage22() { return message22; };
	inline std::string& getMessage23() { return message23; };
	inline std::string& getMessage24() { return message24; };
	inline std::string& getMessage25() { return message25; };
	inline std::string& getMessage26() { return message26; };
	inline std::string& getMessage27() { return message27; };
	inline std::string& getMessage28() { return message28; };
	inline std::string& getMessage29() { return message29; };
	inline std::string& getMessage30() { return message30; };
	inline std::string& getMessage31() { return message31; };
	inline std::string& getMessage32() { return message32; };
	inline std::string& getMessage33() { return message33; };
	inline std::string& getMessage34() { return message34; };
	inline std::string& getMessage35() { return message35; };
	inline std::string& getMessage36() { return message36; };
	inline std::string& getMessage37() { return message37; };
	inline std::string& getMessage38() { return message38; };
	inline std::string& getMessage39() { return message39; };
	inline std::string& getMessage40() { return message40; };
	inline std::string& getMessage41() { return message41; };
	inline std::string& getMessage42() { return message42; };
	inline std::string& getMessage43() { return message43; };
	inline std::string& getMessage44() { return message44; };
	inline std::string& getMessage45() { return message45; };
	inline std::string& getMessage46() { return message46; };
	inline std::string& getMessage47() { return message47; };
	inline std::string& getMessage48() { return message48; };
	inline std::string& getMessage49() { return message49; };
	inline std::string& getMessage50() { return message50; };
	inline std::string& getMessage51() { return message51; };
	inline std::string& getMessage52() { return message52; };
	inline std::string& getMessage53() { return message53; };
	inline std::string& getMessage54() { return message54; };
	inline std::string& getMessage55() { return message55; };
	inline std::string& getMessage56() { return message56; };
	inline std::string& getMessage57() { return message57; };
	inline std::string& getMessage58() { return message58; };
	inline std::string& getMessage59() { return message59; };
	inline std::string& getMessage60() { return message60; };
	inline std::string& getMessage61() { return message61; };
	inline std::string& getMessage62() { return message62; };
	inline std::string& getMessage63() { return message63; };
	inline std::string& getMessage64() { return message64; };
	inline std::string& getMessage65() { return message65; };
	inline std::string& getMessage66() { return message66; };
	inline std::string& getMessage67() { return message67; };
	inline std::string& getMessage68() { return message68; };
	inline std::string& getMessage69() { return message69; };
	inline std::string& getMessage70() { return message70; };
	inline std::string& getMessage71() { return message71; };
	inline std::string& getMessage72() { return message72; };
	inline std::string& getMessage73() { return message73; };
	inline std::string& getMessage74() { return message74; };
	inline std::string& getMessage75() { return message75; };
	inline std::string& getMessage76() { return message76; };
	inline std::string& getMessage77() { return message77; };

	inline int& getLength() { return length; };
	inline bool& getBypass() { return bypass; };

	// Inherited via IModule
	virtual const char* getModuleName() override;
	virtual const char* getModName() override;
	virtual void onTick(C_GameMode* gm) override;
};