#pragma once
#include "Module.h"
#include "../../../Utils/Target.h"
#include "../ModuleManager.h"
#include <ctime>

class AutoEZv2 : public IModule {
private:

	std::string m1 = "sorry im laggin";
	std::string m2 = "BRO im so laggy";
	std::string m3 = "lag spike sorry";
	std::string m4 = "omg this lag";
	std::string m5 = "Lag";
	std::string m6 = "im lag";
	std::string m7 = "pls no report im just lag";
	std::string m8 = "dude i hate playing at MCDonalds";
	std::string m9 = "this taco bell internet isnt valid";
	std::string m10 = "my internet pls help";
	std::string m11 = "sum1 buy me new wifi";
	std::string m12 = "my internet sucks";
	std::string m13 = "my wifi sucks";
	std::string m14 = "whats my ping wtf";
	std::string m15 = "Bro i have 1000+ ping";
	std::string m16 = "i hate this internet";
	std::string m17 = "im lagging back";
	std::string m18 = "i just lagged back wtf";
	std::string m19 = "pls help";
	std::string m20 = "hive is so laggy";
	std::string m21 = "DUDE i lagged!";
	std::string m22 = "help me pls my internet sucks";
	std::string m23 = "so laggy im shleep";
	std::string m24 = "i swear im lagging";
	std::string m25 = "im so done with this lag bro!";
	std::string m26 = "Im trying to fix my internet!";
	std::string m27 = "lag spike";
	std::string m28 = "pls no kill im laggy";
	std::string m29 = "dude i hate dsl";
	std::string m30 = "im lagging so hard";
	std::string m31 = "im laggin dude";
	std::string m32 = "my connection sucks";
	std::string m33 = "how to fix rubberbanding help";
	std::string m34 = "DUDE! i cant pvp in this lag!";
	std::string m35 = "I think my router died";
	std::string m36 = "this wifi sucks so bad";
	std::string m37 = "DUDE! i cant play at McDonalds anymore";
	std::string m38 = "hive is so laggy for me";
	std::string m39 = "pls help im teleporting";
	std::string m40 = "dude IM LAGGED";
	std::string m41 = "everyones tping for me";
	std::string m42 = "bro the lagback";
	std::string m43 = "i just lagged back dude";
	std::string m44 = "i cant with this lag";
	std::string m45 = "am i being dosed?";
	std::string m46 = "this is so bad";
	std::string m47 = "i cant even play bro";
	std::string m48 = "my wifi is non-existant rn";
	std::string m49 = "sorry i have 1000+ ms";
	std::string m50 = "hive needs to fix the servers";
	std::string m51 = "Im so done with this lag";
	std::string m52 = "My i3 cannot run Minecraft";
	std::string m53 = "lagggg";
	std::string m54 = "imma die cuz of lag";
	std::string m55 = "i need x86";
	std::string m56 = "MY FPS";
	std::string m57 = "MY PING";
	std::string m58 = "anyone know how to fix lag";
	std::string m59 = "i hate playing like this";
	std::string m60 = "the server is so laggy";
	std::string m61 = "Anyone else lagging?";
	std::string m62 = "dude my ethernet unplugged";
	std::string m63 = "dude pls im lagging so hard";
	std::string m64 = "plis bro im rubberbanding";
	std::string m65 = "this is rediculous";
	std::string m66 = "why are the players so laggy";
	std::string m67 = "i cant even hit people!";
	std::string m68 = "i gotta fix my net";
	std::string m69 = "help me the lag is insane";
	std::string m70 = "this is not optimal network condition pls help";
	std::string m71 = "DUDE! why is it so laggy";
	std::string m72 = "my provider sucks";
	std::string m73 = "would a vpn fix my internet? pls help";
	std::string m74 = "i cant with this LAG bro! im boutta rage";
	std::string m75 = "sorry i hate my net";
	std::string m76 = "Can anyone see my msg? im lagging so hard";
	std::string m77 = "i need better internet";
	std::string m78 = "The Lag Is Insane";
	std::string m79 = "my ping sucks";
	std::string m80 = "idk why im teleporting my wifi should be fine";
	std::string m81 = "i lagged so hard";
	std::string m82 = "i think i have malware on my internet";
	std::string m83 = "dude why am I lagging SO HARD";
	std::string m84 = "I need to call my provider";
	std::string m85 = "why am i being dosed bro";
	std::string m86 = "this is so bad i cant even hit ppl";
	std::string m87 = "im lagg";
	std::string m88 = "i need my net fixed";
	std::string m89 = "i cant even pvp with this LAG";
	std::string m90 = "fix the server Hive im so laggy";
	std::string m91 = "mcDonalds wifi is trash";
	std::string m92 = "sorry i need to get out of Taco Bell";
	std::string m93 = "dont hackusate me im just insanely laggy";
	std::string m94 = "PLS";
	std::string m95 = "imma need to get better internet";
	std::string m96 = "my games boutta crash";
	std::string m97 = "i think my wifis dead";
	std::string m98 = "dude im sooooo laggy!!";
	std::string m99 = "i cant even bridge its so laggy";
	std::string m100 = "my blocks delete themselves this is so bad";
	std::string m101 = "help i cant move without lagging back";
	std::string m102 = "Im trying to fix the ping its so bad";
	std::string m103 = "dude plis";
	std::string m104 = "i wish i could fix my internet";
	std::string m105 = "im extrememly sorry for my ping";
	std::string m106 = "My blocks disappear when i bridge";
	std::string m107 = "spare me im laggy";
	std::string m108 = "I think my internet is down";
	std::string m109 = "can someone tell the mcDonalds employee thier wifi is trash";
	std::string m110 = "dude im hitting ppl and its not registering";
	std::string m111 = "if my bridge deletes itself one more time i swear";
	std::string m112 = "Dude hive needs to stop laggin me back";
	std::string m113 = "dude!!";
	std::string m114 = "i wish i could play with good internet";
	std::string m115 = "i need better wifi sorry";
	std::string m116 = "PLS bro im lagged!";
	std::string m117 = "this lag is so annoying!";
	std::string m118 = "i cant play with this lag";
	std::string m119 = "can anyone fix the lag";
	std::string m120 = "boutta die cuz of this lag bro";
	std::string m121 = "im so done with this";
	std::string m122 = "I wish i could move bro";
	std::string m123 = "the hive needa fix the servers";
	std::string m124 = "im lagging back all the time";
	std::string m125 = "give me a moment to try and fix my internet";
	std::string m126 = "ik my internet sucks im so sorry";
	std::string m127 = "dont kill me broski i cant with this lag";
	std::string m128 = "i cant even place without it dissapearing!";
	std::string m129 = "the lagback is insane";
	std::string m130 = "hive loves tping me back";
	std::string m131 = "my net sucks";
	std::string m132 = "i hate this lag its so as";
	std::string m133 = "i can prove its my ping";
	std::string m134 = "this is not enjoyable";
	std::string m135 = "I surrender im so laggy";
	std::string m136 = "im gonna die to this lag dude";
	std::string m137 = "im gonna die to lag this is so trash";
	std::string m138 = "my blocks dont wanna place";
	std::string m139 = "if only i wasnt laggy *sigh*";
	std::string m140 = "my blocks just wont place for some reason";
	std::string m141 = "im being deedosed";
	std::string m142 = "tell these nerds to stop the deedos";
	std::string m143 = "i can prove its just lag";
	std::string m144 = "no report plesae im just a laggy mf";
	std::string m145 = "dude playing like this with 1000+ ms is as";
	std::string m146 = "i tried to fix my ping it made it worse";
	std::string m147 = "this game sucks now im so laggy";
	std::string m148 = "my net is so bad bro";
	std::string m149 = "dont sweat on me i cant even move without lagging";
	std::string m150 = "the lagg is so bad";
	std::string m151 = "how to fix the lag bug";
	std::string m152 = "i cant even play without lagging boutta logoff";
	std::string m153 = "Im tping everywhere";
	std::string m154 = "this is so trash i cant play with this";
	std::string m155 = "dude omg why am i tping";
	std::string m156 = "i cant even do anything with this lag bro";
	std::string m157 = "i gotta upgrade the internet speed";

public:
	int kc = 0;
	bool send = false;

	AutoEZv2();
	~AutoEZv2();

	// Inherited via IModule
	virtual const char* getModuleName() override;
	virtual void onTick(C_GameMode* gm) override;
	virtual void onEnable() override;
	virtual void onDisable() override;
};

