#pragma once
#include "Module.h"
#include "../../../Utils/Target.h"
#include "../ModuleManager.h"
#include <ctime>

class AutoEZ : public IModule {
private:

	std::string m1 = "my gaming chair runs u";
	std::string m2 = "ur bad";
	std::string m3 = "L";
	std::string m4 = "ezz";
	std::string m5 = "ur so as";
	std::string m6 = "i run u";
	std::string m7 = "ur as";
	std::string m8 = "stay mad";
	std::string m9 = "you are big mad";
	std::string m10 = "keep crying";
	std::string m11 = "my gaming chair owns u";
	std::string m12 = "ur mad";
	std::string m13 = "trash";
	std::string m14 = "tossed";
	std::string m15 = "ur so bad";
	std::string m16 = "ez mop";
	std::string m17 = "violated.";
	std::string m18 = "you just got mopped";
	std::string m19 = "stay down";
	std::string m20 = "u are not valid";
	std::string m21 = "ur so mad";
	std::string m22 = "keep raging";
	std::string m23 = "i own u";
	std::string m24 = "L ost.";
	std::string m25 = "take dis L";
	std::string m26 = "how mad 1/10";
	std::string m27 = "mad cuz bad";
	std::string m28 = "im just too valid";
	std::string m29 = "600+ confirmed bypasses";
	std::string m30 = "you just got ran";
	std::string m31 = "you ape";
	std::string m32 = "i think ur big mad";
	std::string m33 = "how mad are u 1/10";
	std::string m34 = "im best pvp";
	std::string m35 = "i run Hive";
	std::string m36 = "ur so as at this game";
	std::string m37 = "report me im really scared";
	std::string m38 = "u just got ran up on";
	std::string m39 = "get owned";
	std::string m40 = "lol ur so as";
	std::string m41 = "stop trying ur so bad";
	std::string m42 = "ah yes all team on me i dare you";
	std::string m43 = "gaming chair too op";
	std::string m44 = "imagine dying";
	std::string m45 = "if ur so mad then leave";
	std::string m46 = "RQ i run u";
	std::string m47 = "get out my lobby";
	std::string m48 = "hive anticheat is non-existant";
	std::string m49 = "how mad are u rn";
	std::string m50 = "keep sweating buddy ur not good";
	std::string m51 = "i ran you out my lobby";
	std::string m52 = "im insane at the craft";
	std::string m53 = "i shot u up";
	std::string m54 = "ur dead bro";
	std::string m55 = "RQ i own u";
	std::string m56 = "I run you all";
	std::string m57 = "try again when ur valid at the game";
	std::string m58 = "U should have RQed";
	std::string m59 = "my gaming chair is just too OP";
	std::string m60 = "you are mad i hack";
	std::string m61 = "hive bigmad";
	std::string m62 = "sweaty ape has been eliminated";
	std::string m63 = "if u report ur mad";
	std::string m64 = "just too sweaty for hive";
	std::string m65 = "u are now dead";
	std::string m66 = "ur mad hes mad shes mad";
	std::string m67 = "im no hak";
	std::string m68 = "ape down";
	std::string m69 = "keep raging buddy";
	std::string m70 = "the hive just doesnt have an anticheat";
	std::string m71 = "hive anticheat is not effective";
	std::string m72 = "ur dead";
	std::string m73 = "ezz mop";
	std::string m74 = "im not getting kicked";
	std::string m75 = "bhoppin and now ur games ended";
	std::string m76 = "its all over now rq";
	std::string m77 = "bop bop u are now mopped";
	std::string m78 = "stop spam placing ur not good";
	std::string m79 = "I dont hack i just have the OP gaming chair";
	std::string m80 = "stop hackusating";
	std::string m81 = "rlly am i just too good";
	std::string m82 = "sweating wont help";
	std::string m83 = "hive anticheat is good amirite";
	std::string m84 = "stay salty";
	std::string m85 = "u cant kill me";
	std::string m86 = "ur big noob";
	std::string m87 = "sweat harder next time";
	std::string m88 = "sorry but your time on the hive network has ended";
	std::string m89 = "run my 1s";
	std::string m90 = "stop auto clicking ur not good";
	std::string m91 = "LOL";
	std::string m92 = "imagine hacking";
	std::string m93 = "hackusated.";
	std::string m94 = "I'm not hacking its just my new gaming chair";
	std::string m95 = "im too good bro";
	std::string m96 = "get off this game ur as";
	std::string m97 = "I have 600+ confirmed bypasses";
	std::string m98 = "mopped u";
	std::string m99 = "u were shot up bop bop";
	std::string m100 = "stop with the spam placing";
	std::string m101 = "hes hacking!1!1!11";
	std::string m102 = "imagine exploiting";
	std::string m103 = "im not hacking you're just bad!";
	std::string m104 = "imagine cheating";
	std::string m105 = "hop off ur as";
	std::string m106 = "too valid keep crying";
	std::string m107 = "You tried, you died.";
	std::string m108 = "Better luck next time";
	std::string m109 = "No one beats me";
	std::string m110 = "How are you so bad? just practice your aim and hold w";
	std::string m111 = "Report me to microsoft";
	std::string m112 = "ur fuming";
	std::string m113 = "cry";
	std::string m114 = "jajaja :v";
	std::string m115 = "report me to the hive network";
	std::string m116 = "false report bozo";
	std::string m117 = "my gaming chair is just too good";
	std::string m118 = "report me bozo im shaking in my boots";
	std::string m119 = "ezz bypass";
	std::string m120 = "u can try but u will die";
	std::string m121 = "U quickdropped";
	std::string m122 = "I dropped u";
	std::string m123 = "1v1 me bro";
	std::string m124 = "negative IQ";
	std::string m125 = "whats the point of cheating";
	std::string m126 = "sorry but u lost bozo";
	std::string m127 = "my gaming chair is immune to Hive's Anticheat";
	std::string m128 = "stop placing ur as";
	std::string m129 = "u cant kill me i run u";
	std::string m130 = "sweat mad";
	std::string m131 = "just another kill to my kill count";
	std::string m132 = "just void bro";
	std::string m133 = "bypass lvl insane";
	std::string m134 = "hive runs u";
	std::string m135 = "Surrender rn";
	std::string m136 = "Hackusated.";
	std::string m137 = "its all over now";
	std::string m138 = "LOL get gud";
	std::string m139 = "handed u the L";
	std::string m140 = "im just the best pvp";
	std::string m141 = "hop off me bro ur as";
	std::string m142 = "get better";
	std::string m143 = "ur gonna report me?";
	std::string m144 = "shiver me timbers no report plesae";
	std::string m145 = "too ez";
	std::string m146 = "ur a clown";
	std::string m147 = "light work";
	std::string m148 = "didnt even have to sweat";
	std::string m149 = "runnin thru these sweats";
	std::string m150 = "dont even say nothin to me ur bad";
	std::string m151 = "someones raging";
	std::string m152 = "i win every time";
	std::string m153 = "u have been killed";
	std::string m154 = "ur game is now ended";
	std::string m155 = "rq why are u still here";
	std::string m156 = "just shot an opp up";
	std::string m157 = "0 DTR";

public:
	int kc = 0;
	bool send = false;

	AutoEZ();
	~AutoEZ();

	// Inherited via IModule
	virtual const char* getModuleName() override;
	virtual void onTick(C_GameMode* gm) override;
	virtual void onEnable() override;
	virtual void onDisable() override;
};

