#pragma once
#include "Module.h"
#include "../../../Utils/Target.h"
#include "../ModuleManager.h"
#include <ctime>

class AutoEZv3 : public IModule {
private:

	std::string m1 = "It was that terrifying feeling you have as you tightly hold the covers over you with the knowledge that there is something hiding under your bed. You want to look, but you dont at the same time. Youre frozen";
	std::string m2 = "Love isnt always a ray of sunshine. Thats what the older girls kept telling her when she said she had found the perfect man. She had thought this was simply bitter talk on their part since they had been";
	std::string m3 = "He had done everything right. There had been no mistakes throughout the entire process. It had been perfection and he knew it without a doubt, but the results still stared back at him with the fact that he had lost.";
	std::string m4 = "He knew what he was supposed to do. That had been apparent from the beginning. That was what made the choice so difficult. What he was supposed to do and what he would do were not the same. This";
	std::string m5 = "Dave found joy in the daily routine of life. He awoke at the same time, ate the same breakfast and drove the same commute. He worked at a job that never seemed to change and he got home at 6 pm sharp";
	std::string m6 = "I don’t like cats and they don’t like me. I used to be allergic to them and I would get stuffed up and have hives. That doesn’t seem to happen anymore. But I still don’t like them. I lived with 3 cats that were not";
	std::string m7 = "The words hadnt flowed from his fingers for the past few weeks. He never imagined hed find himself with writers block, but here he sat with a blank screen in front of him. That blank screen taunting";
	std::string m8 = "Sometimes its the first moment of the day that catches you off guard. Thats what Wendy was thinking. She opened her window to see fire engines screeching down the street. While this wasnt";
	std::string m9 = "He took a sip of the drink. He wasnt sure whether he liked it or not, but at this moment it didnt matter. She had made it especially for him so he would have forced it down even if he had absolutely hated it.";
	std::string m10 = "He had disappointed himself more than anyone else. That wasnt to say that he hadnt disappointed others. The fact was that he had disappointed a lot of people who were close to him. The fact that they";
	std::string m11 = "You can decide what you want to do in life, but I suggest doing something that creates. Something that leaves a tangible thing once youre done. That way even after youre gone, you will still live on in the";
	std::string m12 = "The thing thats great about this job is the time sourcing the items involves no traveling. I just look online to buy it. Its really as simple as that. While everyone else is searching for what they can sell, I sit";
	std::string m13 = "The fog was as thick as pea soup. This was a problem. Gary was driving but couldnt see a thing in front of him. He knew he should stop, but the road was narrow so if he did, it would be right in the";
	std::string m14 = "Turning away from the ledge, he started slowly down the mountain, deciding that he would, that very night, satisfy his curiosity about the man-house. In the meantime, he would go down into the canyon";
	std::string m15 = "The headache wouldnt go away. Shes taken medicine but even that didnt help. The monstrous throbbing in her head continued. She had this happen to her only once before in her life and she";
	std::string m16 = "There was only one way to do things in the Statton house. That one way was to do exactly what the father, demanded. He made the decisions and everyone else followed without question. That";
	std::string m17 = "Colors bounced around in her head. They mixed and threaded themselves together. Even colors that had no business being together. They were all one, yet distinctly separate at the same time. How was she";
	std::string m18 = "It had been her dream for years but Dana had failed to take any action toward making it come true. There had always been a good excuse to delay or prioritize another project. As she woke, she realized";
	std::string m19 = "It all started with a random letter. Several of those were joined forces to create a random word. The words decided to get together and form a random sentence. They decided not to stop there and it";
	std::string m20 = "It was hidden under the log beside the stream. It had been there for as long as he had been alive. He wasnt sure if anyone besides him and his friends knew of its existence. He knew that anyone could";
	std::string m21 = "She put the pen to paper but she couldnt bring herself to actually write anything. She just stared at the blank card and wondered what words she could write that would help in even a small way. She";
	std::string m22 = "It had been a rough day. Things hadnt gone as planned and that meant she got yelled at by her boss. It didnt even matter that it wasnt her fault. When things went wrong at work, got the";
	std::string m23 = "Sleeping in his car was never the plan but sometimes things dont work out as planned. This had been his life for the last three months and he was just beginning to get used to it. He didnt";
	std::string m24 = "It really didnt matter what they did to him. Hes already made up his mind. Whatever came his way, he was prepared for the consequences. He knew in his heart that the sacrifice he made was done with";
	std::string m25 = "The clowns had taken over. And yes, they were literally clowns. Over 100 had appeared out of a small VW bug that had been driven up to the bank. Now they were all inside and had taken it over.";
	std::string m26 = "He stepped away from the mic. This was the best take he had done so far, but something seemed missing. Then it struck him all at once. Visuals ran in front of his eyes and music rang in his ears. His";
	std::string m27 = "He heard the loud impact before he ever saw the result. It had been so loud that it had actually made him jump back in his seat. As soon as he recovered from the surprise, he saw the crack in the";
	std::string m28 = "As she sat watching the world go by, something caught her eye. It wasnt so much its color or shape, but the way it was moving. She squinted to see if she could better understand what it was and where";
	std::string m29 = "it was going, but it didnt help. As she continued to stare into the distance, she didnt understand why this uneasiness was building inside her body. She felt like she should get up and run. If only she could";
	std::string m30 = "It was a concerning development that he couldnt get out of his mind. Hed had many friends throughout his early years and had fond memories of playing with them, but he couldnt understand";
	std::string m31 = "There wasnt a whole lot more that could be done. It had become a wait-and-see situation with the final results no longer in her control. That didnt stop her from trying to control the situation. She demanded";
	std::string m32 = "It was going to rain. The weather forecast didnt say that, but the steel plate in his hip did. He had learned over the years to trust his hip over the weatherman. It was going to rain, so he better get";
	std::string m33 = "Was it enough? That was the question he kept asking himself. Was being satisfied enough? He looked around him at everyone yearning to just be satisfied in their daily life and he had reached that";
	std::string m34 = "She has seen this scene before. It had come to her in dreams many times before. She had to pinch herself to make sure it wasnt a dream again. As her fingers squeezed against her arm, she felt the pain. It was";
	std::string m35 = "The amber droplet hung from the branch, reaching fullness and ready to drop. It waited. While many of the other droplets were satisfied to form as big as they could and release, this droplet had other plans.";
	std::string m36 = "It wanted to be part of history. It wanted to be remembered long after all the other droplets had dissolved into history. So it waited for the perfect specimen to fly by to trap and capture that it hoped";
	std::string m37 = "Her mom had warned her. She had been warned time and again, but she had refused to believe her. She had done everything right and she knew she would be rewarded for doing so with the promotion.";
	std::string m38 = "They had no proof. He knew that they knew he had done it but they didnt have any proof. It was a huge distinction and it was the difference between him keeping his freedom or being locked away for";
	std::string m39 = "He couldnt remember exactly where he had read it, but he was sure that he had. The fact that she didnt believe him was quite frustrating as he began to search the Internet to find the article. It wasnt as if it";
	std::string m40 = "There once lived an old man and an old woman who were peasants and had to work hard to earn their daily bread. The old man used to go to fix fences and do other odd jobs for the farmers around, and while";
	std::string m41 = "The red glow of tail lights indicating another long drive home from work after an even longer 24-hour shift at the hospital. The shift hadn’t been horrible but the constant stream of patients entering the ER";
	std::string m42 = "She wondered if the note had reached him. She scolded herself for not handing it to him in person. She trusted her friend, but so much could happen. She waited impatiently for word.";
	std::string m43 = "The blinking light caught her attention. She thought about it a bit and couldnt remember ever noticing it before. That was strange since it was obvious the flashing light had been there for years. Now she";
	std::string m44 = "The time to take action was now. All three men knew in their hearts this was the case, yet none of them moved a muscle to try. They were all watching and waiting for one of the others to make the first";
	std::string m45 = "What were the chances? It would have to be a lot more than 100 to 1. It was likely even more than 1,000 to 1. The more he thought about it, the odds of it happening had to be more than 10,000 to 1 and even";
	std::string m46 = "an exaggeration of an unlikely event, but he could see that they may actually be accurate in this situation. Whatever the odds of it happening, he knew they were big. What he didnt know was";
	std::string m47 = "There were about twenty people on the dam. Most of them were simply walking and getting exercise. There were a few who were fishing. There was a family who had laid down a blanket and they were";
	std::string m48 = "It was the best compliment that hed ever received although the person who gave it likely never knew. It had been an off-hand observation on his ability to hold a conversation and actually add pertinent";
	std::string m49 = "information to it on practically any topic. Although he hadnt consciously strived to be able to do so, hed started to voraciously read the news when he couldnt keep up on topics his friends discussed";
	std::string m50 = "The fact that someone had noticed enough to compliment him that he could talk intelligently about many topics meant that he had succeeded in his quest to be better informed.";
	std::string m51 = "She put the pen to paper but she couldnt bring herself to actually write anything. She just stared at the blank card and wondered what words she could write that would help in even a small way. She";
	std::string m52 = "There werent supposed to be dragons flying in the sky. First and foremost, dragons didnt exist. They were mythical creatures from fantasy books like unicorns. This was something that Pete knew in his";
	std::string m53 = "Her hair was a tangled mess which she tried to make presentable by putting in a lump on the top of her head. It didnt really work although it was a valiant attempt. While most people simply noticed";
	std::string m54 = "wanted to be famous. The problem was that she had never considered all the downsides to actually being famous. Had she taken the time to objectively consider these downsides, she would have never";
	std::string m55 = "found joy in the daily routine of life. He awoke at the same time, ate the same breakfast and drove the same commute. He worked at a job that never seemed to change and he got home at 6 pm sharp";
	std::string m56 = "Life isnt always beautiful. That was a lesson that was learning. He also realized that life wasnt easy. This had come as a shock since he had lived a charmed life. He hated that this was the truth and";
	std::string m57 = "He wouldnt realize until much later in life that the difficult obstacles he was facing that were taking away the beauty in his life at this moment would ultimately make his life much more beautiful. All he knew";
	std::string m58 = "They told her that this was her once chance to show the world what she was made of. She believed them at the time. It was the big stage and she knew the world would be there to see. The only one who had";
	std::string m59 = "disagreed with this sentiment was her brother. He had told her that you dont show the world what youre made of when they are all watching, you show that in your actions when nobody was looking.";
	std::string m60 = "The wave crashed and hit the sandcastle head-on. The sandcastle began to melt under the waves force and as the wave receded, half the sandcastle was gone. The next wave hit, not quite as strong, but still";
	std::string m61 = "managed to cover the remains of the sandcastle and take more of it away. The third wave, a big one, crashed over the sandcastle completely covering and engulfing it. When it receded, there was no";
	std::string m62 = "I love the feel of wood curls flying off the lathe as I begin to shape the log in front of me. The sound of scraping changes based on the wetness of the wood, the speed at which the lathe is turning, and";
	std::string m63 = "the type of cut I am making. The smell and feel of wet wood being turned are unique. The water is sprayed out as I cut through the different layers of wood. A log can turn into anything ones";
	std::string m64 = "imagination can think of with the right set of hands-on tools. I have those hands and imagination. I use all of my senses and intuition to create a beautiful object. That is why I enjoy turning wood.";
	std::string m65 = "As she sat watching the world go by, something caught her eye. It wasnt so much its color or shape, but the way it was moving. She squinted to see if she could better understand what it was and where";
	std::string m66 = "There was a time when this wouldnt have bothered her. The fact that it did actually bother her bothered her even more. What had changed in her life that such a small thing could annoy her so much for the";
	std::string m67 = "it would upset someone. It seemed like such a silly reason for people to get upset but she knew the minute that she began to consider doing it that there was no way everyone in her life would be";
	std::string m68 = "It was simply a question of who she would rather displease most. While this had always been her parents, and especially her mom, in the past that she tried to keep from upsetting, she decided that this time";
	std::string m69 = "How had she been so wrong? All her instincts and intuition completely failed her for the first time in her life. She had so heavily relied on both when making decisions up until this moment and she felt";
	std::string m70 = "a seismic shift take place in her self-confidence. If she could be so completely wrong about something so simple as this, how could she make decisions about really important things taking place in her";
	std::string m71 = "to explore an area that would be adventurous and exciting. As the others in the group all shited to the right, he slipped past the danger sign to begin an adventure he would later regret.";
	std::string m72 = "There were a variety of ways to win the game. he had played it long enough to know most of them and he could see what his opponent was trying to do. There was a simple counterattack that he";
	std::string m73 = "who had been in this situation a thousand times in the past. So, it was with great surprise when his opponent used a move he had never before seen or anticipated to easily defeat him in the game.";
	std::string m74 = "He stepped away from the mic. This was the best take he had done so far, but something seemed missing. Then it struck him all at once. Visuals ran in front of his eyes and music rang in his ears. His";
	std::string m75 = "Thats all the note said. There was no indication from where it came or who may have written it. Had it been meant for someone else? Meghan looked around the room, but nobody made eye contact back. For a brief moment";
	std::string m76 = "Its not his fault. I know youre going to want to, but you cant blame him. He really has no idea how it happened. I kept trying to come up with excuses I could say to mom that would keep her calm when";
	std::string m77 = "Pink ponies and purple giraffes roamed the field. Cotton candy grew from the ground as a chocolate river meandered off to the side. What looked like stones in the pasture were actually rock candy.";
	std::string m78 = "He wondered if he should disclose the truth to his friends. It would be a risky move. Yes, the truth would make things a lot easier if they all stayed on the same page, but the truth might fracture the";
	std::string m79 = "She was in a hurry. Not the standard hurry when youre in a rush to get someplace, but a frantic hurry. The type of hurry where a few seconds could mean life or death. She raced down the road ignoring";
	std::string m80 = "The opened package of potato chips held the answer to the mystery. Both detectives looked at it but failed to realize it was the key to solve the crime. They passed by it assuming it was random trash";
	std::string m81 = "He knew what he was supposed to do. That had been apparent from the beginning. That was what made the choice so difficult. What he was supposed to do and what he would do were not the same. This";
	std::string m82 = "Turning away from the ledge, he started slowly down the mountain, deciding that he would, that very night, satisfy his curiosity about the man-house. In the meantime, he would go down into the canyon";
	std::string m83 = "and get a cool drink, after which he would visit some berry patches just over the ridge, and explore among the foothills a bit before his nap-time, which always came just after the sun had walked past the";
	std::string m84 = "middle of the sky. At that period of the day the sun’s warm rays seemed to cast a sleepy spell over the silent mountainside, so all of the animals, with one accord, had decided it should be the hour for their";
	std::string m85 = "It seemed like it should have been so simple. There was nothing inherently difficult with getting the project done. It was simple and straightforward enough that even a child should have been able to";
	std::string m86 = "Her eyebrows were a shade darker than her hair. They were thick and almost horizontal, emphasizing the depth of her eyes. She was rather handsome than beautiful. Her face was captivating by reason of";
	std::string m87 = "It really doesnt matter what she thinks as it isnt her problem to solve. Thats what he kept trying to convince himself. She was trying to insert her opinion where it wasnt wanted or welcome. He";
	std::string m88 = "It probably seemed trivial to most people, but it mattered to her. She wasnt sure why it mattered so much to her, but she understood deep within her being that it mattered to her. So for the 365th day in";
	std::string m89 = "His mother had always taught him not to ever think of himself as better than others. Hed tried to live by this motto. He never looked down on those who were less fortunate or who had less money than";
	std::string m90 = "Many people say that life isnt like a bed of roses. I beg to differ. I think that life is quite like a bed of roses. Just like life, a bed of roses looks pretty on the outside, but when youre in it, you find that it is";
	std::string m91 = "My pincher collar is snapped on. Then comes the electric zapper collar. Finally, my purple at-home collar is taken off and I know I’m going for a walk to the dog park. I’m so excited to see my friends. I hope";
	std::string m92 = "wild on the sidewalks. They don’t listen to their humans. I know I could ignore mine but if I do she may zap me and it’s just not worth it. She probably wouldn’t let me back at the dog park if I didn’t listen";
	std::string m93 = "I havent bailed on writing. Look, Im generating a random paragraph at this very moment in an attempt to get my writing back on track. I am making an effort. I will start writing consistently";
	std::string m94 = "What was beyond the bend in the stream was unknown. Both were curious, but only one was brave enough to want to explore. That was the problem. There was always one that let fear rule her life.";
	std::string m95 = "Shes asked the question so many times that she barely listened to the answers anymore. The answers were always the same. Well, not exactly the same, but the same in a general sense. A more accurate";
	std::string m96 = "The light blinded him. It was dark and he thought he was the only one in the area, but the light shining in his eyes proved him wrong. It came from about 100 feet away and was shining so directly into his";
	std::string m97 = "person holding the light. There was only one thing to do in this situation. He reached into his pocket and pulled out a flashlight of his own that was much stronger than the one currently blinding him. He";
	std::string m98 = "I recently discovered I could make fudge with just chocolate chips, sweetened condensed milk, vanilla extract, and a thick pot on slow heat. I tried it with dark chocolate chunks and I tried it with semi-sweet";
	std::string m99 = "chocolate chips. Its better with both kinds. It comes out pretty bad with just the dark chocolate. The best add-ins are crushed almonds and marshmallows what you get from that is Rocky Road. It takes about";
	std::string m100 = "twenty minutes from start to fridge, and then it takes about six months to work off the twenty pounds you gain from eating it. All things in moderation, friends. All things in moderation.";
	std::string m101 = "She didnt like the food. She never did. She made the usual complaints and started the tantrum he knew was coming. But this time was different. Instead of trying to placate her and her unreasonable";
	std::string m102 = "Puppies are soft, cute, funny, and make a big mess. Every month or two our family fosters 6-12 week old puppies for a puppy rescue nonprofit organization. We all enjoy cuddling their furry bodies after a clean";
	std::string m103 = "100,000 to 1. People often threw around the chances of something happening as being 1,000,000 to 1 as an exaggeration of an unlikely event, but he could see that they may actually be accurate in this";
	std::string m104 = "out of his comfort zone and made him try new things hed never imagine doing otherwise. Up to this point, this had been a good thing. It had expanded his experiences and given him a new";
	std::string m105 = "shook her head seeing if that would help. It didnt. Although it seemed beyond reality, there was no denying she was witnessing a large formation of alien spaceships filling the sky.";
	std::string m106 = "All he wanted was a candy bar. It didnt seem like a difficult request to comprehend, but the clerk remained frozen and didnt seem to want to honor the request. It might have had something to do with";
	std::string m107 = "She didnt understand how changed worked. When she looked at today compared to yesterday, there was nothing that she could see that was different. Yet, when she looked at today compared to last year,";
	std::string m108 = "There had to be a better way. Thats all Nancy could think as she sat at her desk staring at her computer screen. Shed already spent five years of her life in this little cubicle staring at her computer doing";
	std::string m109 = "It was a simple tip of the hat. Grace didnt think that anyone else besides her had even noticed it. It wasnt anything that the average person would notice, let alone remember at the end of the day.";
	std::string m110 = "Do you think youre living an ordinary life? You are so mistaken its difficult to even explain. The mere fact that you exist makes you extraordinary. The odds of you existing are less than winning the lottery, but";
	std::string m111 = "Was it a whisper or was it the wind? He wasnt quite sure. He thought he heard a voice but at this moment all he could hear was the wind rustling the leaves of the trees all around him. He stopped and";
	std::string m112 = "listened more intently to see if he could hear the voice again. Nothing but the wind rustling the leaves could be heard. He was about to continue his walk when he felt a hand on his shoulder, and he";
	std::string m113 = "The shoes had been there for as long as anyone could remember. In fact, it was difficult for anyone to come up with a date they had first appeared. It had seemed theyd always been there and yet they";
	std::string m114 = "seemed so out of place. Why nobody had removed them was a question that had been asked time and again, but while they all thought it, nobody had ever found the energy to actually do it. So, the shoes";
	std::string m115 = "Sometimes it just doesnt make sense. The man walking down the street in a banana suit. The llama standing in the middle of the road. The fairies dancing in front of the car window. The fact that all";
	std::string m116 = "such a small thing could annoy her so much for the entire day? She knew it was ridiculous that she even took notice of it, yet she was still obsessing over it as she tried to fall asleep.";
	std::string m117 = "He lifted the bottle to his lips and took a sip of the drink. He had tasted this before, but he couldnt quite remember the time and place it had happened. He desperately searched his mind trying";
	std::string m118 = "She patiently waited for his number to be called. She had no desire to be there, but her mom had insisted that she go. Shes resisted at first, but over time she realized it was simply easier to appease her and go.";
	std::string m119 = "eye contact back. For a brief moment, she thought it might be a message for her to follow her dreams, but ultimately decided it was easier to ignore it as she crumpled it up and threw it away.";
	std::string m120 = "The rain was coming. Everyone thought this would be a good thing. It hadnt rained in months and the earth was dry as a bone. It wasnt a surprise that everyone thought a good rain was what was";
	std::string m121 = "Then came the night of the first falling star. It was seen early in the morning, rushing over Winchester eastward, a line of flame high in the atmosphere. Hundreds must have seen it and taken it for an";
	std::string m122 = "He had done everything right. There had been no mistakes throughout the entire process. It had been perfection and he knew it without a doubt, but the results still stared back at him with the fact that he";
	std::string m123 = "He dropped the ball. While most people would think that this was a metaphor of some type, in his case it was absolutely literal. He had hopes of reaching the Major League and that dream was now it great";
	std::string m124 = "It was easy to spot her. All you needed to do was look at her socks. They were never a matching pair. One would be green while the other would be blue. One would reach her knee while the other barely";
	std::string m125 = "I havent bailed on writing. Look, Im generating a random paragraph at this very moment in an attempt to get my writing back on track. I am making an effort. I will start writing consistently";
	std::string m126 = "managed to cover the remains of the sandcastle and take more of it away. The third wave, a big one, crashed over the sandcastle completely covering and engulfing it. When it receded, there was no";
	std::string m127 = "He picked up the burnt end of the branch and made a mark on the stone. Day 52 if the marks on the stone were accurate. He couldnt be sure. Day and nights had begun to blend together creating";
	std::string m128 = "She reached her goal, exhausted. Even more chilling to her was that the euphoria that she thought shed feel upon reaching it wasnt there. Something wasnt right. Was this the only feeling shed have for over";
	std::string m129 = "He heard the song coming from a distance, lightly floating over the air to his ears. Although it was soft and calming, he was wary. It seemed a little too soft and a little too calming for everything that was going on.";
	std::string m130 = "He stepped away from the mic. This was the best take he had done so far, but something seemed missing. Then it struck him all at once. Visuals ran in front of his eyes and music rang in his ears. His";
	std::string m131 = "They needed to find a place to eat. The kids were beginning to get grumpy in the back seat and if they didnt find them food soon, it was just a matter of time before they were faced with a complete";
	std::string m132 = "seemed to be an impossible no-win situation where not everyone would be happy no matter where they decided to eat which in itself would lead to a meltdown. Yet a decision needed to be made and it";
	std::string m133 = "The choice was red, green, or blue. It didnt seem like an important choice when he was making it, but it was a choice nonetheless. Had he known the consequences at that time, he would likely have";
	std::string m134 = "There was something beautiful in his hate. It wasnt the hate itself as it was a disgusting display of and intolerance. It was what propelled the hate and the fact that although he had this hate, he didnt";
	std::string m135 = "He was tired. Not the normal every day tired from a hard day o work. The exhausted type of tired where youre surprised your body can even move. All he wanted to do was sit in front of the TV, put his";
	std::string m136 = "It all started with the computer. Had he known what was to follow, he would have never logged on that day. But the truth was there was no way to know what was about to happen. So he pressed the";
	std::string m137 = "The lone lamp post of the one-street town flickered, not quite dead but definitely on its way out. Suitcase by her side, she paid no heed to the light, the street or the town. A car was coming down the street and";
	std::string m138 = "wasnt anything that the average person would notice, let alone remember at the end of the day. Thats why it seemed so unbelievable that this little gesture would ultimately change the course of the world.";
	std::string m139 = "Shes asked the question so many times that she barely listened to the answers anymore. The answers were always the same. Well, not exactly the same, but the same in a general sense. A more accurate";
	std::string m140 = "He stared out the window at the snowy field. Hed been stuck in the house for close to a month and his only view of the outside world was through the window. There wasnt much to see. It was mostly just";
	std::string m141 = "the field with an occasional bird or small animal who ventured into the field. As he continued to stare out the window, he wondered how much longer hed be shackled to the steel bar inside the house.";
	std::string m142 = "wasnt long before a random paragraph had been cobbled together. The question was whether or not they could continue the momentum long enough to create a random short story.";
	std::string m143 = "It was a question of which of the two she preferred. On the one hand, the choice seemed simple. The more expensive one with a brand name would be the choice of most. It was the easy choice. The safe";
	std::string m144 = "truly understand. She was in love and wanted him to feel the same way. He didnt, and no matter how he tried to explain to her she refused to listen or to understand.";
	std::string m145 = "One dollar and eighty-seven cents. That was all. And sixty cents of it was in pennies. Pennies saved one and two at a time by bulldozing the grocer and the vegetable man and the butcher until one’s cheeks";
	std::string m146 = "He walked down the steps from the train station in a bit of a hurry knowing the secrets in the briefcase must be secured as quickly as possible. Bounding down the steps, he heard something behind him";
	std::string m147 = "Indescribable oppression, which seemed to generate in some unfamiliar part of her consciousness, filled her whole being with a vague anguish. It was like a shadow, like a mist passing";
	std::string m148 = "Fate, which had directed her footsteps to the path which they had taken. She was just having a good cry all to herself. The mosquitoes made merry over her, biting her firm, round arms and nipping at her";
	std::string m149 = "The leather jacked showed the scars of being his favorite for years. It wore those scars with pride, feeling that they enhanced his presence rather than diminishing it. The scars gave it character and had";
	std::string m150 = "clean and orderly, it still ended up looking like a mess in a couple of days. What she didnt know was there was a tiny creature living in it that didnt like things neat.";
	std::string m151 = "It seemed like it should have been so simple. There was nothing inherently difficult with getting the project done. It was simple and straightforward enough that even a child should have been able to";
	std::string m152 = "The box sat on the desk next to the computer. It had arrived earlier in the day and business had interrupted her opening it earlier. She didnt who had sent it and briefly wondered who it might have";
	std::string m153 = "It was their first date and she had been looking forward to it the entire week. She had her eyes on him for months, and it had taken a convoluted scheme with several friends to make it happen, but";
	std::string m154 = "every time you open your mouth and speak. You make so many choices like this that you never even think about, but you have the choice with each one. What are you going to do with this knowledge?";
	std::string m155 = "again, but while they all thought it, nobody had ever found the energy to actually do it. So, the shoes remained on the steps, out of place in one sense, but perfectly normal in another.";
	std::string m156 = "Youre going to make a choice today that will have a direct impact on where you are five years from now. The truth is, youll make choice like that every day of your life. The problem is that on most days, you";
	std::string m157 = "wont know the choice you make will have such a huge impact on your life in the future. So if you want to end up in a certain place in the future, you need to be careful of the choices you make today.";

public:
	int kc = 0;
	bool send = false;

	AutoEZv3();
	~AutoEZv3();

	// Inherited via IModule
	virtual const char* getModuleName() override;
	virtual void onTick(C_GameMode* gm) override;
	virtual void onEnable() override;
	virtual void onDisable() override;
};

